#!/bin/bash

RABBITMQ_NODENAME=${RABBITMQ_NODENAME:-rabbit}

if [ -z "$CLUSTER_WITH" ]; then
  echo "Running as single server"
  rabbitmq-server
else
  echo "Running as clustered server"
  /usr/sbin/rabbitmq-server -detached

  if [[ ! -z $(rabbitmqctl cluster_status | grep $CLUSTER_WITH) ]]; then
    echo Alerady joined;
  else
    rabbitmqctl stop_app
    rabbitmqctl reset
    rabbitmqctl -n $RABBITMQ_NODENAME@$CLUSTER_WITH forget_cluster_node  $RABBITMQ_NODENAME@$HOSTNAME
    echo "Joining cluster $CLUSTER_WITH"
    rabbitmqctl join_cluster ${ENABLE_RAM:+--ram} $RABBITMQ_NODENAME@$CLUSTER_WITH
    rabbitmqctl start_app
  fi;
  # Tail to keep the a foreground process active..
  tail -f /var/log/rabbitmq/*
fi
